### ISSUE TITLE
UI changes for the Logical Definitions

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#121]
The UI elements of the Logical Definitions should use the same styles as the ones from the Forms, as much as possible.

The figure explains some of the needed changes, and they are also explained below the figure:

<img width="843" alt="image" src="https://github.com/user-attachments/assets/808b4801-d1a5-4ce7-8009-5efa48ab3bca">

- [x] The logical definition and necessary condition tables should span the entire width available. The axis column should be fixed width, and the value should take the rest of the width
- [x] The title "Logical definitions" should be renamed to "Logical Definitions" and should use the same style as the forms title ("Base index terms" in the image)
- [x] The label "Logical definition superclass :" should be renamed to: "Logical Definition Superclass:" (no space) and should be bold
- [x] Between the title "Logical Definitions" and the label "Logical Definition Superclass:" there should be less space
- [x] The headers of the logical definitions and necessary conditions tables should be the same style as the one from the form shown in the figure (same height, color, font, etc.)
- [x] The rows of the logical definitions and necessary conditions tables should be the same style as the one from the form shown in the figure (same height, color, font, etc.)
- [x] The waste basket delete icons (for the log defs and the rows) should be replaced with the gray/red circle with an X icon used for deletion in forms. The icon changes it color from gray to red when the mouse slides over it. 
- [x] The delete icon for the logical definition superclass should be placed where the table ends, aligned with the end of the table
- [x] The add log def icon should be replaced with the plus gray/green icon used in the forms. There should be some left-padding added, so that it is not too close to the title
- [x] The width of the drop down for the axis should span the entire width of the cell, and it should show "Select axis" (gray, italics font) for empty value.
- [x] The drop down for the value will likely be replaced with something else. There should be a text saying "Select value" (gray, italics font)  if nothing is selected.
- [x] The axes in the drop down should be ordered by the order used in the postcoordination table (e.g. starts with Severity, etc). The allowed and required axes are shown first also in the postcoordination table order.
- [x] There should be a question mark icon used in the forms for Help in the title lines for "Logical Definitions" and "Necessary Conditions"
- [x] There should be no placeholder image, if there are no log defs or necessary conditions.
- [ ] #124

**Comment by csnyulas** [comment]
- [ ] Align table header for Logical Definition axis value and Necessary Condition axis value vertically centered
![image](https://github.com/user-attachments/assets/bced69e5-c30d-4c53-b9e2-ecd7019e6d44)

- [ ] Show the correct tooltip for the icons in the Post-coordination Value Set card views:
![image](https://github.com/user-attachments/assets/6dd30755-a11b-4600-9231-72dcfdd20594)
![image](https://github.com/user-attachments/assets/16dae697-4382-4623-8cb5-4246392b2c57)

- [ ] Present the Post-coordination axes in the dropdown for Logical Definition and Necessary Conditions listed in their "natural" order (as they are specified in the backend configuration and shown in the Post-Coordination table, because that has a business logic to it for the users). If there are grouped by Required/Allowed/Not Allowed, the "natural" order should be followed within each group
- [ ] The Allowed and Required Post-coordination axis in the dropdown for Logical Definition should be shown in **bold**, for more prominence, and to help color blind people, and for rendering on devices where colors may not be visible, or clearly differentiating enough. Optionally include a separator line between the Allowed and Not Allowed lists (no need to include a separator between Required and Allowed groups)

**Comment by csnyulas** [comment]
@soimugeoWB can you please link the issues that you created for the unchecked items. Without that this issue is can not be considered complete.

**Comment by soimugeoWB** [comment]
I've created issue #140 for the tooltips of the scale value cards, which isn't really related to logical definitions.

Testing the final two issues about sorting the postcoordination axis and having the allowed and required axis as bold seem to be already implemented. The part regarding the separator can't be done because of a gwt limitation from what i remember.
![Image](https://github.com/user-attachments/assets/e08f265a-d1d8-49e9-8177-331f11552768)

Keep in mind that the current logical definitions only take effect based on the MMS linearization from the postcoordination table.
