### ISSUE TITLE
WebProtégé loads very slowly, not cached

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#32]
It seems that the cache.js file is not cached, although it should be.

Here are the calls for loading WebProtégé:
<img width="1041" alt="image" src="https://github.com/who-icatx/icatx-project/assets/2709502/1053b2fe-c469-4d16-92d2-f7358d80e6fd">

Then, load in the same browser, different tab, again. Notice that the cache.js file which is 91MB big, is loaded again. Should have been cached.

<img width="1045" alt="image" src="https://github.com/who-icatx/icatx-project/assets/2709502/4d0f8247-0fb7-4a89-b260-9d9e45ab2b8c">

**Comment by matthewhorridge** [comment]
This isn't the production file.  That file is 7-8 MB.  Needs rebuilding with the release profile.

**Comment by soimugeoWB** [comment]
Ok, with profile webprotege.stanford.edu that cache file is 7.6 mb. 
![image](https://github.com/who-icatx/icatx-project/assets/149394944/71d3f47d-1375-4cf6-a762-9b4be90c5b8b)

however the project still take a bit of time to load, so that cache file was not the issue i think.
In the same time the projects load instantly with no noticeable delay on local. previously there were some delays also on local.

**Comment by matthewhorridge** [comment]
I believe this issue is stale.  Please re-open if not.
