### ISSUE TITLE
Configure access policies for WHOFIC editors

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#46]
For the release, regular editors should not be able to delete classes. And possibly other operations will be banned.

**Comment by soimugeoWB** [comment]
this is partially fixed 
![image](https://github.com/who-icatx/icatx-project/assets/149394944/df96f973-153f-4586-b9b4-fc99b1d8a752)

I need to figure out why the button is just being disabled instead of hiding it.

**Comment by soimugeoWB** [comment]
Actually i realised this is not implemented correctly. In this current implementation the application does not chare if you have that role on a specific project as long if you have that role. This needs to be reimplemented so that we check both the project and the role you have assigned on that project.
